# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/testofhiphop/helloworld-0.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/testofhiphop/helloworld-0.1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/testofhiphop/helloworld-0.1/CMakeFiles /usr/src/testofhiphop/helloworld-0.1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/testofhiphop/helloworld-0.1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helloworld-hphp

# Build rule for target.
helloworld-hphp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld-hphp
.PHONY : helloworld-hphp

# fast build rule for target.
helloworld-hphp/fast:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/build
.PHONY : helloworld-hphp/fast

php/test2.o: php/test2.cpp.o
.PHONY : php/test2.o

# target to build an object file
php/test2.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/php/test2.cpp.o
.PHONY : php/test2.cpp.o

php/test2.i: php/test2.cpp.i
.PHONY : php/test2.i

# target to preprocess a source file
php/test2.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/php/test2.cpp.i
.PHONY : php/test2.cpp.i

php/test2.s: php/test2.cpp.s
.PHONY : php/test2.s

# target to generate assembly for a file
php/test2.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/php/test2.cpp.s
.PHONY : php/test2.cpp.s

sys/class_map.o: sys/class_map.cpp.o
.PHONY : sys/class_map.o

# target to build an object file
sys/class_map.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/class_map.cpp.o
.PHONY : sys/class_map.cpp.o

sys/class_map.i: sys/class_map.cpp.i
.PHONY : sys/class_map.i

# target to preprocess a source file
sys/class_map.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/class_map.cpp.i
.PHONY : sys/class_map.cpp.i

sys/class_map.s: sys/class_map.cpp.s
.PHONY : sys/class_map.s

# target to generate assembly for a file
sys/class_map.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/class_map.cpp.s
.PHONY : sys/class_map.cpp.s

sys/cpputil.o: sys/cpputil.cpp.o
.PHONY : sys/cpputil.o

# target to build an object file
sys/cpputil.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/cpputil.cpp.o
.PHONY : sys/cpputil.cpp.o

sys/cpputil.i: sys/cpputil.cpp.i
.PHONY : sys/cpputil.i

# target to preprocess a source file
sys/cpputil.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/cpputil.cpp.i
.PHONY : sys/cpputil.cpp.i

sys/cpputil.s: sys/cpputil.cpp.s
.PHONY : sys/cpputil.s

# target to generate assembly for a file
sys/cpputil.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/cpputil.cpp.s
.PHONY : sys/cpputil.cpp.s

sys/dynamic_table_class.o: sys/dynamic_table_class.cpp.o
.PHONY : sys/dynamic_table_class.o

# target to build an object file
sys/dynamic_table_class.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_class.cpp.o
.PHONY : sys/dynamic_table_class.cpp.o

sys/dynamic_table_class.i: sys/dynamic_table_class.cpp.i
.PHONY : sys/dynamic_table_class.i

# target to preprocess a source file
sys/dynamic_table_class.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_class.cpp.i
.PHONY : sys/dynamic_table_class.cpp.i

sys/dynamic_table_class.s: sys/dynamic_table_class.cpp.s
.PHONY : sys/dynamic_table_class.s

# target to generate assembly for a file
sys/dynamic_table_class.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_class.cpp.s
.PHONY : sys/dynamic_table_class.cpp.s

sys/dynamic_table_constant.o: sys/dynamic_table_constant.cpp.o
.PHONY : sys/dynamic_table_constant.o

# target to build an object file
sys/dynamic_table_constant.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_constant.cpp.o
.PHONY : sys/dynamic_table_constant.cpp.o

sys/dynamic_table_constant.i: sys/dynamic_table_constant.cpp.i
.PHONY : sys/dynamic_table_constant.i

# target to preprocess a source file
sys/dynamic_table_constant.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_constant.cpp.i
.PHONY : sys/dynamic_table_constant.cpp.i

sys/dynamic_table_constant.s: sys/dynamic_table_constant.cpp.s
.PHONY : sys/dynamic_table_constant.s

# target to generate assembly for a file
sys/dynamic_table_constant.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_constant.cpp.s
.PHONY : sys/dynamic_table_constant.cpp.s

sys/dynamic_table_file.o: sys/dynamic_table_file.cpp.o
.PHONY : sys/dynamic_table_file.o

# target to build an object file
sys/dynamic_table_file.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_file.cpp.o
.PHONY : sys/dynamic_table_file.cpp.o

sys/dynamic_table_file.i: sys/dynamic_table_file.cpp.i
.PHONY : sys/dynamic_table_file.i

# target to preprocess a source file
sys/dynamic_table_file.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_file.cpp.i
.PHONY : sys/dynamic_table_file.cpp.i

sys/dynamic_table_file.s: sys/dynamic_table_file.cpp.s
.PHONY : sys/dynamic_table_file.s

# target to generate assembly for a file
sys/dynamic_table_file.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_file.cpp.s
.PHONY : sys/dynamic_table_file.cpp.s

sys/dynamic_table_func.o: sys/dynamic_table_func.cpp.o
.PHONY : sys/dynamic_table_func.o

# target to build an object file
sys/dynamic_table_func.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_func.cpp.o
.PHONY : sys/dynamic_table_func.cpp.o

sys/dynamic_table_func.i: sys/dynamic_table_func.cpp.i
.PHONY : sys/dynamic_table_func.i

# target to preprocess a source file
sys/dynamic_table_func.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_func.cpp.i
.PHONY : sys/dynamic_table_func.cpp.i

sys/dynamic_table_func.s: sys/dynamic_table_func.cpp.s
.PHONY : sys/dynamic_table_func.s

# target to generate assembly for a file
sys/dynamic_table_func.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/dynamic_table_func.cpp.s
.PHONY : sys/dynamic_table_func.cpp.s

sys/global_state.o: sys/global_state.cpp.o
.PHONY : sys/global_state.o

# target to build an object file
sys/global_state.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state.cpp.o
.PHONY : sys/global_state.cpp.o

sys/global_state.i: sys/global_state.cpp.i
.PHONY : sys/global_state.i

# target to preprocess a source file
sys/global_state.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state.cpp.i
.PHONY : sys/global_state.cpp.i

sys/global_state.s: sys/global_state.cpp.s
.PHONY : sys/global_state.s

# target to generate assembly for a file
sys/global_state.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state.cpp.s
.PHONY : sys/global_state.cpp.s

sys/global_state_class_static_variables.no.o: sys/global_state_class_static_variables.no.cpp.o
.PHONY : sys/global_state_class_static_variables.no.o

# target to build an object file
sys/global_state_class_static_variables.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_class_static_variables.no.cpp.o
.PHONY : sys/global_state_class_static_variables.no.cpp.o

sys/global_state_class_static_variables.no.i: sys/global_state_class_static_variables.no.cpp.i
.PHONY : sys/global_state_class_static_variables.no.i

# target to preprocess a source file
sys/global_state_class_static_variables.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_class_static_variables.no.cpp.i
.PHONY : sys/global_state_class_static_variables.no.cpp.i

sys/global_state_class_static_variables.no.s: sys/global_state_class_static_variables.no.cpp.s
.PHONY : sys/global_state_class_static_variables.no.s

# target to generate assembly for a file
sys/global_state_class_static_variables.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_class_static_variables.no.cpp.s
.PHONY : sys/global_state_class_static_variables.no.cpp.s

sys/global_state_dynamic_constants.no.o: sys/global_state_dynamic_constants.no.cpp.o
.PHONY : sys/global_state_dynamic_constants.no.o

# target to build an object file
sys/global_state_dynamic_constants.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_dynamic_constants.no.cpp.o
.PHONY : sys/global_state_dynamic_constants.no.cpp.o

sys/global_state_dynamic_constants.no.i: sys/global_state_dynamic_constants.no.cpp.i
.PHONY : sys/global_state_dynamic_constants.no.i

# target to preprocess a source file
sys/global_state_dynamic_constants.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_dynamic_constants.no.cpp.i
.PHONY : sys/global_state_dynamic_constants.no.cpp.i

sys/global_state_dynamic_constants.no.s: sys/global_state_dynamic_constants.no.cpp.s
.PHONY : sys/global_state_dynamic_constants.no.s

# target to generate assembly for a file
sys/global_state_dynamic_constants.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_dynamic_constants.no.cpp.s
.PHONY : sys/global_state_dynamic_constants.no.cpp.s

sys/global_state_fiber.no.o: sys/global_state_fiber.no.cpp.o
.PHONY : sys/global_state_fiber.no.o

# target to build an object file
sys/global_state_fiber.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_fiber.no.cpp.o
.PHONY : sys/global_state_fiber.no.cpp.o

sys/global_state_fiber.no.i: sys/global_state_fiber.no.cpp.i
.PHONY : sys/global_state_fiber.no.i

# target to preprocess a source file
sys/global_state_fiber.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_fiber.no.cpp.i
.PHONY : sys/global_state_fiber.no.cpp.i

sys/global_state_fiber.no.s: sys/global_state_fiber.no.cpp.s
.PHONY : sys/global_state_fiber.no.s

# target to generate assembly for a file
sys/global_state_fiber.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_fiber.no.cpp.s
.PHONY : sys/global_state_fiber.no.cpp.s

sys/global_state_method_static_inited.no.o: sys/global_state_method_static_inited.no.cpp.o
.PHONY : sys/global_state_method_static_inited.no.o

# target to build an object file
sys/global_state_method_static_inited.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_inited.no.cpp.o
.PHONY : sys/global_state_method_static_inited.no.cpp.o

sys/global_state_method_static_inited.no.i: sys/global_state_method_static_inited.no.cpp.i
.PHONY : sys/global_state_method_static_inited.no.i

# target to preprocess a source file
sys/global_state_method_static_inited.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_inited.no.cpp.i
.PHONY : sys/global_state_method_static_inited.no.cpp.i

sys/global_state_method_static_inited.no.s: sys/global_state_method_static_inited.no.cpp.s
.PHONY : sys/global_state_method_static_inited.no.s

# target to generate assembly for a file
sys/global_state_method_static_inited.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_inited.no.cpp.s
.PHONY : sys/global_state_method_static_inited.no.cpp.s

sys/global_state_method_static_variables.no.o: sys/global_state_method_static_variables.no.cpp.o
.PHONY : sys/global_state_method_static_variables.no.o

# target to build an object file
sys/global_state_method_static_variables.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_variables.no.cpp.o
.PHONY : sys/global_state_method_static_variables.no.cpp.o

sys/global_state_method_static_variables.no.i: sys/global_state_method_static_variables.no.cpp.i
.PHONY : sys/global_state_method_static_variables.no.i

# target to preprocess a source file
sys/global_state_method_static_variables.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_variables.no.cpp.i
.PHONY : sys/global_state_method_static_variables.no.cpp.i

sys/global_state_method_static_variables.no.s: sys/global_state_method_static_variables.no.cpp.s
.PHONY : sys/global_state_method_static_variables.no.s

# target to generate assembly for a file
sys/global_state_method_static_variables.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_method_static_variables.no.cpp.s
.PHONY : sys/global_state_method_static_variables.no.cpp.s

sys/global_state_pseudomain_variables.no.o: sys/global_state_pseudomain_variables.no.cpp.o
.PHONY : sys/global_state_pseudomain_variables.no.o

# target to build an object file
sys/global_state_pseudomain_variables.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_pseudomain_variables.no.cpp.o
.PHONY : sys/global_state_pseudomain_variables.no.cpp.o

sys/global_state_pseudomain_variables.no.i: sys/global_state_pseudomain_variables.no.cpp.i
.PHONY : sys/global_state_pseudomain_variables.no.i

# target to preprocess a source file
sys/global_state_pseudomain_variables.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_pseudomain_variables.no.cpp.i
.PHONY : sys/global_state_pseudomain_variables.no.cpp.i

sys/global_state_pseudomain_variables.no.s: sys/global_state_pseudomain_variables.no.cpp.s
.PHONY : sys/global_state_pseudomain_variables.no.s

# target to generate assembly for a file
sys/global_state_pseudomain_variables.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_pseudomain_variables.no.cpp.s
.PHONY : sys/global_state_pseudomain_variables.no.cpp.s

sys/global_state_redeclared_classes.no.o: sys/global_state_redeclared_classes.no.cpp.o
.PHONY : sys/global_state_redeclared_classes.no.o

# target to build an object file
sys/global_state_redeclared_classes.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_classes.no.cpp.o
.PHONY : sys/global_state_redeclared_classes.no.cpp.o

sys/global_state_redeclared_classes.no.i: sys/global_state_redeclared_classes.no.cpp.i
.PHONY : sys/global_state_redeclared_classes.no.i

# target to preprocess a source file
sys/global_state_redeclared_classes.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_classes.no.cpp.i
.PHONY : sys/global_state_redeclared_classes.no.cpp.i

sys/global_state_redeclared_classes.no.s: sys/global_state_redeclared_classes.no.cpp.s
.PHONY : sys/global_state_redeclared_classes.no.s

# target to generate assembly for a file
sys/global_state_redeclared_classes.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_classes.no.cpp.s
.PHONY : sys/global_state_redeclared_classes.no.cpp.s

sys/global_state_redeclared_functions.no.o: sys/global_state_redeclared_functions.no.cpp.o
.PHONY : sys/global_state_redeclared_functions.no.o

# target to build an object file
sys/global_state_redeclared_functions.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_functions.no.cpp.o
.PHONY : sys/global_state_redeclared_functions.no.cpp.o

sys/global_state_redeclared_functions.no.i: sys/global_state_redeclared_functions.no.cpp.i
.PHONY : sys/global_state_redeclared_functions.no.i

# target to preprocess a source file
sys/global_state_redeclared_functions.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_functions.no.cpp.i
.PHONY : sys/global_state_redeclared_functions.no.cpp.i

sys/global_state_redeclared_functions.no.s: sys/global_state_redeclared_functions.no.cpp.s
.PHONY : sys/global_state_redeclared_functions.no.s

# target to generate assembly for a file
sys/global_state_redeclared_functions.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_redeclared_functions.no.cpp.s
.PHONY : sys/global_state_redeclared_functions.no.cpp.s

sys/global_state_static_global_variables.no.o: sys/global_state_static_global_variables.no.cpp.o
.PHONY : sys/global_state_static_global_variables.no.o

# target to build an object file
sys/global_state_static_global_variables.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_static_global_variables.no.cpp.o
.PHONY : sys/global_state_static_global_variables.no.cpp.o

sys/global_state_static_global_variables.no.i: sys/global_state_static_global_variables.no.cpp.i
.PHONY : sys/global_state_static_global_variables.no.i

# target to preprocess a source file
sys/global_state_static_global_variables.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_static_global_variables.no.cpp.i
.PHONY : sys/global_state_static_global_variables.no.cpp.i

sys/global_state_static_global_variables.no.s: sys/global_state_static_global_variables.no.cpp.s
.PHONY : sys/global_state_static_global_variables.no.s

# target to generate assembly for a file
sys/global_state_static_global_variables.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_state_static_global_variables.no.cpp.s
.PHONY : sys/global_state_static_global_variables.no.cpp.s

sys/global_variables.o: sys/global_variables.cpp.o
.PHONY : sys/global_variables.o

# target to build an object file
sys/global_variables.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_variables.cpp.o
.PHONY : sys/global_variables.cpp.o

sys/global_variables.i: sys/global_variables.cpp.i
.PHONY : sys/global_variables.i

# target to preprocess a source file
sys/global_variables.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_variables.cpp.i
.PHONY : sys/global_variables.cpp.i

sys/global_variables.s: sys/global_variables.cpp.s
.PHONY : sys/global_variables.s

# target to generate assembly for a file
sys/global_variables.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/global_variables.cpp.s
.PHONY : sys/global_variables.cpp.s

sys/literal_strings_0.no.o: sys/literal_strings_0.no.cpp.o
.PHONY : sys/literal_strings_0.no.o

# target to build an object file
sys/literal_strings_0.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/literal_strings_0.no.cpp.o
.PHONY : sys/literal_strings_0.no.cpp.o

sys/literal_strings_0.no.i: sys/literal_strings_0.no.cpp.i
.PHONY : sys/literal_strings_0.no.i

# target to preprocess a source file
sys/literal_strings_0.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/literal_strings_0.no.cpp.i
.PHONY : sys/literal_strings_0.no.cpp.i

sys/literal_strings_0.no.s: sys/literal_strings_0.no.cpp.s
.PHONY : sys/literal_strings_0.no.s

# target to generate assembly for a file
sys/literal_strings_0.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/literal_strings_0.no.cpp.s
.PHONY : sys/literal_strings_0.no.cpp.s

sys/main.o: sys/main.cpp.o
.PHONY : sys/main.o

# target to build an object file
sys/main.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/main.cpp.o
.PHONY : sys/main.cpp.o

sys/main.i: sys/main.cpp.i
.PHONY : sys/main.i

# target to preprocess a source file
sys/main.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/main.cpp.i
.PHONY : sys/main.cpp.i

sys/main.s: sys/main.cpp.s
.PHONY : sys/main.s

# target to generate assembly for a file
sys/main.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/main.cpp.s
.PHONY : sys/main.cpp.s

sys/name_maps.o: sys/name_maps.cpp.o
.PHONY : sys/name_maps.o

# target to build an object file
sys/name_maps.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/name_maps.cpp.o
.PHONY : sys/name_maps.cpp.o

sys/name_maps.i: sys/name_maps.cpp.i
.PHONY : sys/name_maps.i

# target to preprocess a source file
sys/name_maps.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/name_maps.cpp.i
.PHONY : sys/name_maps.cpp.i

sys/name_maps.s: sys/name_maps.cpp.s
.PHONY : sys/name_maps.s

# target to generate assembly for a file
sys/name_maps.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/name_maps.cpp.s
.PHONY : sys/name_maps.cpp.s

sys/scalar_arrays.no.o: sys/scalar_arrays.no.cpp.o
.PHONY : sys/scalar_arrays.no.o

# target to build an object file
sys/scalar_arrays.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays.no.cpp.o
.PHONY : sys/scalar_arrays.no.cpp.o

sys/scalar_arrays.no.i: sys/scalar_arrays.no.cpp.i
.PHONY : sys/scalar_arrays.no.i

# target to preprocess a source file
sys/scalar_arrays.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays.no.cpp.i
.PHONY : sys/scalar_arrays.no.cpp.i

sys/scalar_arrays.no.s: sys/scalar_arrays.no.cpp.s
.PHONY : sys/scalar_arrays.no.s

# target to generate assembly for a file
sys/scalar_arrays.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays.no.cpp.s
.PHONY : sys/scalar_arrays.no.cpp.s

sys/scalar_arrays_0.no.o: sys/scalar_arrays_0.no.cpp.o
.PHONY : sys/scalar_arrays_0.no.o

# target to build an object file
sys/scalar_arrays_0.no.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays_0.no.cpp.o
.PHONY : sys/scalar_arrays_0.no.cpp.o

sys/scalar_arrays_0.no.i: sys/scalar_arrays_0.no.cpp.i
.PHONY : sys/scalar_arrays_0.no.i

# target to preprocess a source file
sys/scalar_arrays_0.no.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays_0.no.cpp.i
.PHONY : sys/scalar_arrays_0.no.cpp.i

sys/scalar_arrays_0.no.s: sys/scalar_arrays_0.no.cpp.s
.PHONY : sys/scalar_arrays_0.no.s

# target to generate assembly for a file
sys/scalar_arrays_0.no.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/scalar_arrays_0.no.cpp.s
.PHONY : sys/scalar_arrays_0.no.cpp.s

sys/source_info.o: sys/source_info.cpp.o
.PHONY : sys/source_info.o

# target to build an object file
sys/source_info.cpp.o:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/source_info.cpp.o
.PHONY : sys/source_info.cpp.o

sys/source_info.i: sys/source_info.cpp.i
.PHONY : sys/source_info.i

# target to preprocess a source file
sys/source_info.cpp.i:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/source_info.cpp.i
.PHONY : sys/source_info.cpp.i

sys/source_info.s: sys/source_info.cpp.s
.PHONY : sys/source_info.s

# target to generate assembly for a file
sys/source_info.cpp.s:
	$(MAKE) -f CMakeFiles/helloworld-hphp.dir/build.make CMakeFiles/helloworld-hphp.dir/sys/source_info.cpp.s
.PHONY : sys/source_info.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... helloworld-hphp"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... php/test2.o"
	@echo "... php/test2.i"
	@echo "... php/test2.s"
	@echo "... sys/class_map.o"
	@echo "... sys/class_map.i"
	@echo "... sys/class_map.s"
	@echo "... sys/cpputil.o"
	@echo "... sys/cpputil.i"
	@echo "... sys/cpputil.s"
	@echo "... sys/dynamic_table_class.o"
	@echo "... sys/dynamic_table_class.i"
	@echo "... sys/dynamic_table_class.s"
	@echo "... sys/dynamic_table_constant.o"
	@echo "... sys/dynamic_table_constant.i"
	@echo "... sys/dynamic_table_constant.s"
	@echo "... sys/dynamic_table_file.o"
	@echo "... sys/dynamic_table_file.i"
	@echo "... sys/dynamic_table_file.s"
	@echo "... sys/dynamic_table_func.o"
	@echo "... sys/dynamic_table_func.i"
	@echo "... sys/dynamic_table_func.s"
	@echo "... sys/global_state.o"
	@echo "... sys/global_state.i"
	@echo "... sys/global_state.s"
	@echo "... sys/global_state_class_static_variables.no.o"
	@echo "... sys/global_state_class_static_variables.no.i"
	@echo "... sys/global_state_class_static_variables.no.s"
	@echo "... sys/global_state_dynamic_constants.no.o"
	@echo "... sys/global_state_dynamic_constants.no.i"
	@echo "... sys/global_state_dynamic_constants.no.s"
	@echo "... sys/global_state_fiber.no.o"
	@echo "... sys/global_state_fiber.no.i"
	@echo "... sys/global_state_fiber.no.s"
	@echo "... sys/global_state_method_static_inited.no.o"
	@echo "... sys/global_state_method_static_inited.no.i"
	@echo "... sys/global_state_method_static_inited.no.s"
	@echo "... sys/global_state_method_static_variables.no.o"
	@echo "... sys/global_state_method_static_variables.no.i"
	@echo "... sys/global_state_method_static_variables.no.s"
	@echo "... sys/global_state_pseudomain_variables.no.o"
	@echo "... sys/global_state_pseudomain_variables.no.i"
	@echo "... sys/global_state_pseudomain_variables.no.s"
	@echo "... sys/global_state_redeclared_classes.no.o"
	@echo "... sys/global_state_redeclared_classes.no.i"
	@echo "... sys/global_state_redeclared_classes.no.s"
	@echo "... sys/global_state_redeclared_functions.no.o"
	@echo "... sys/global_state_redeclared_functions.no.i"
	@echo "... sys/global_state_redeclared_functions.no.s"
	@echo "... sys/global_state_static_global_variables.no.o"
	@echo "... sys/global_state_static_global_variables.no.i"
	@echo "... sys/global_state_static_global_variables.no.s"
	@echo "... sys/global_variables.o"
	@echo "... sys/global_variables.i"
	@echo "... sys/global_variables.s"
	@echo "... sys/literal_strings_0.no.o"
	@echo "... sys/literal_strings_0.no.i"
	@echo "... sys/literal_strings_0.no.s"
	@echo "... sys/main.o"
	@echo "... sys/main.i"
	@echo "... sys/main.s"
	@echo "... sys/name_maps.o"
	@echo "... sys/name_maps.i"
	@echo "... sys/name_maps.s"
	@echo "... sys/scalar_arrays.no.o"
	@echo "... sys/scalar_arrays.no.i"
	@echo "... sys/scalar_arrays.no.s"
	@echo "... sys/scalar_arrays_0.no.o"
	@echo "... sys/scalar_arrays_0.no.i"
	@echo "... sys/scalar_arrays_0.no.s"
	@echo "... sys/source_info.o"
	@echo "... sys/source_info.i"
	@echo "... sys/source_info.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

